#name: Build and Deploy to Aliyun
#
#on:
#  push:
#    branches:
#      - master
#
#jobs:
#  build-and-deploy:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v3
#
#      - name: Set up JDK 11
#        uses: actions/setup-java@v3
#        with:
#          java-version: '11'
#          distribution: 'temurin'
#
#      - name: Build with Maven
#        run: mvn clean package -DskipTests
#
##      - name: Deploy to Aliyun Server
##        uses: appleboy/ssh-action@master
##        with:
##          host: ${{ secrets.ALIYUN_SERVER_IP_BOT }}
##          username: ${{ secrets.SSH_USER }}
##          key: ${{ secrets.SSH_KEY_BOT }}
##          script: |
##            mkdir -p /bot
##            cd /bot
##            pkill -f 'java -jar'
##            cp ${GITHUB_WORKSPACE}/target/*.jar ./app.jar
##            nohup java -jar app.jar > app.log 2>&1 &
